library/library/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from libraryMontevideo import urls as mdeo_urls
from libraryMontevideo import views
urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'montevideo/', include(mdeo_urls, namespace='mdeo')),
]

library/libraryMontevideo/urls.py
from django.conf.urls import url
from .views import BookDetailView, BookListView, AuthorListView, AuthorDetailView, from_create_author_view,from_create_book_view
app_name = "mdeoapp"
urlpatterns = [
    url(r'^book/detail/(?P<pk>[\d]+)/$', BookDetailView.as_view(), name='book-detail'),
    url(r'^book/list/$', BookListView.as_view(), name='book-list'),
    url(r'^book/create/$', from_create_book_view, name='book-create'),
    url(r'^author/detail/(?P<pk>[\d]+)/$', AuthorDetailView.as_view(), name='author-detail'),
    url(r'^author/list/$', AuthorListView.as_view(), name='author-list'),
    url(r'^author/create/$', from_create_author_view, name='author-create'),
]

library/libraryMontevideo/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Author(models.Model):
    name = models.CharField(max_length=64)
    is_female = models.BooleanField()
    ocupation = models.CharField(max_length=64)
    email = models.EmailField(max_length=254)

    def __str__(self):
        return (self.name +' '+ self.last_name)

class Book(models.Model):
    date = models.DateField()
    name = models.CharField(max_length=264)
    pages = models.SmallIntegerField()
    author = models.ManyToManyField(Author)
    topic = models.CharField(max_length=264)

    def __str__(self):
        return self.name

library/libraryMontevideo/forms.py
from django import forms

from .models import Author, Book


class AuthorForm(forms.ModelForm):

    class Meta:
        model = Author
        fields = ('name','is_female', 'ocupation','email',)

        widgets = {
            'name': forms.TextInput(attrs={'class': 'textinputclass'}),
            'ocupation': forms.TextInput(attrs={'class': 'textinputclass'}),
            'email': forms.TextInput(attrs={'class': 'emailinputclass'}),
        }


class BookForm(forms.ModelForm):

    class Meta:
        model = Book

        fields = ('date', 'name','pages','author','topic',)

        widgets = {
            'date': forms.DateField(),
            'name': forms.TextInput(attrs={'class': 'textinputclass'}),
            'pages': forms.IntegerField(),
            'topic': forms.Textarea(attrs={'class': 'editable medium-editor-textarea'}),
        }

library/libraryMontevideo/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from . import forms

from .models import Book,Author
# Create your views here.

class BookDetailView(DetailView):
    model = Book
    template_name= 'book_detail.html'
    def get_context_data(self, **kwargs):
        context = super(BookDetailView, self).get_context_data(**kwargs)
        return context

class BookListView(ListView):
    model = Book
    template_name= 'book_list.html'
    paginate_by = 10
    def get_context_data(self, **kwargs):
         context = super(BookListView, self).get_context_data(**kwargs)
         object_list = Book.objects.all()
         context['object_list']=object_list
         return context

def index(request):
    return render(request,'index.html')

def from_create_author_view(request):
    form = forms.AuthorForm()
    return render(request,'author_form.html',{'form':form})

def from_create_book_view(request):
    form = forms.BookForm()
    return render(request,'book_form.html',{'form':form})



class AuthorDetailView(DetailView):
    model = Author
    template_name= 'author_detail.html'
    def get_context_data(self, **kwargs):
        context = super(AuthorDetailView, self).get_context_data(**kwargs)
        return context

class AuthorListView(ListView):
    model = Author
    template_name= 'author_list.html'
    paginate_by = 10
    def get_context_data(self, **kwargs):
         context = super(AuthorListView, self).get_context_data(**kwargs)
         object_list = Author.objects.all()
         context['object_list']=object_list
         return context

library/libraryMontevideo/templates/author_detail.html
<!DOCTYPE html>

{% extends "base.html" %}
    {% block body_block%}
    <div class="media" style="margin-top:50px">
      <img width="100" height="100"  src="https://lh6.googleusercontent.com/proxy/AgD2G1debsPmwO39aDhF4qLWm1GJ2iFGu_ctF4Psh-NY4lBBqvQpKyyJRd7oZVTRfEYtiJqqaHptNQXwulyCdw5Wu82VoQcIX7V3P1DqBCO1nw" class="mr-3">
      <div class="media-body">
        <h5 class="mt-0">Ahutor  Detail</h5>
          <p>Name: {{ author.name }}</p>
          {%if author.is_female %}
            <p>Gender: Female</p>
          {%else%}
            <p>Gender: Male</p>
          {%endif%}
            <p>ocupation: {{ author.ocupation }}</p>
          <p>email: {{ author.email }}</p>
          {% for books in author.book_set.all %}
            <div class="media">
              <img width="60" height="30"  src="https://cco.ca/wp-content/uploads/2019/06/Book-Icon-01-768x432.png" class="align-self-center mr-3">
              <div class="media-body">
                <h5 class="mt-0">Book</h5>
                <p>Title: {{books.name}}</p>
                <p>Topic:  {{books.topic}}</p>
              </div>
            </div>
          {% empty %}
              empty list!
          {%endfor%}
      </div>
    </div>

    {% endblock %}

library/libraryMontevideo/templates/author_form.html
{% extends 'base.html' %}

{% block content %}
    <h1>New Author</h1>

    <form method="POST" class="post-form">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit" class="save btn btn-default">Save</button>
    </form>

    <script>var editor = new MediumEditor('.editable');</script>

{% endblock %}

library/libraryMontevideo/templates/author_list.html
<!DOCTYPE html>
{% extends "base.html" %}
{% block body_block%}
  <h1>Authors</h1>
  <ul class="list-group">
    {% for author in page_obj  %}
      <li  class="list-group-item">
        <table >
          <th>
              <div float='left'><img width="50" height="50" src="https://lh6.googleusercontent.com/proxy/AgD2G1debsPmwO39aDhF4qLWm1GJ2iFGu_ctF4Psh-NY4lBBqvQpKyyJRd7oZVTRfEYtiJqqaHptNQXwulyCdw5Wu82VoQcIX7V3P1DqBCO1nw" alt="book"></div>
          </th>
          <th align="left">
            <div>
              <a href="{% url 'mdeo:author-detail' author.id %}"><p>Name: {{ author.name }}</p></a>
              <p>Ocupation: {{ author.ocupation }}</p>
            </div>
          </th>
        </table>
      </li>
    {% empty %}
      <li>No authors yet.</li>
    {% endfor %}
</ul>
<nav aria-label="Page navigation example">
  <ul class="pagination">

      {% if page_obj.has_previous %}
        <li class="page-item"><a href="?page={{ page_obj.previous_page_number }}" class="page-link" >Previous</a></li>
      {% endif %}
       <li class="current page-item active "><a class="page-link" >{{ page_obj.number }}</a></li>

      {% if page_obj.has_next %}
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">next</a></li>
      {% endif %}

  </ul>
</nav>

{% endblock %}

library/libraryMontevideo/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" >Nozama</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="nav-item nav-link active" href="{% url 'admin:index' %}">Admin</a>
          <a class="nav-item nav-link active" href="{% url 'mdeo:book-create' %}">Create Books</a>
          <a class="nav-item nav-link active" href="{% url 'mdeo:book-list' %}">List of Books</a>
          <a class="nav-item nav-link active" href="{% url 'mdeo:author-create' %}">Create Authors</a>
          <a class="nav-item nav-link active" href="{% url 'mdeo:author-list' %}">List of Authors</a>



        </div>
      </div>
    </nav>

    <div class="container">
    {% block body_block %}
    {# Anything outside of this will be inherited if you use extend.#}
    {% endblock %}
    </div>


  </body>
</html>

library/libraryMontevideo/templates/book_detail.html
<!DOCTYPE html>
{% extends "base.html" %}
    {% block body_block%}
      <h1>Book Detail</h1>
      <p>Name: {{ book.name }}</p>
      <p>Pages: {{ book.pages }}</p>
      <p>Topic: {{ book.topic }}</p>
      <p>Date: {{ book.date }}</p>
      {% for autors in book.author.all %}
        <p>Authors: {{autors.name}}</p>
      {% empty %}
          empty list!
      {%endfor%}
    {% endblock %}

library/libraryMontevideo/templates/book_form.html
{% extends 'base.html' %}

{% block content %}
    <h1>New Book</h1>

    <form method="POST" class="post-form">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit" class="save btn btn-default">Save</button>
    </form>

    <script>var editor = new MediumEditor('.editable');</script>

{% endblock %}

library/libraryMontevideo/templates/book_list.html
<!DOCTYPE html>
{% extends "base.html" %}
{% block body_block%}
  <h1>Books</h1>
  <ul class="list-group">
    {% for book in page_obj  %}
      <li  class="list-group-item">
        <table >
          <th>
              <div float='left'><img width="100" height="50" src="https://cco.ca/wp-content/uploads/2019/06/Book-Icon-01-768x432.png" alt="book"></div>
          </th>
          <th align="left">
            <div>
              <a href="{% url 'mdeo:book-detail' book.id %}"><p>Name: {{ book.name }}</p></a>
              <p>Pages: {{ book.pages }}</p>
              <p>Topic: {{ book.topic }}</p>
            </div>
          </th>
        </table>
      </li>
    {% empty %}
      <li>No books yet.</li>
    {% endfor %}
</ul>
<nav aria-label="Page navigation example">
  <ul class="pagination">

      {% if page_obj.has_previous %}
        <li class="page-item"><a href="?page={{ page_obj.previous_page_number }}" class="page-link" >Previous</a></li>
      {% endif %}
       <li class="current page-item active "><a class="page-link" >{{ page_obj.number }}</a></li>

      {% if page_obj.has_next %}
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">next</a></li>
      {% endif %}

  </ul>
</nav>

{% endblock %}

library/libraryMontevideo/templates/index.html
<!DOCTYPE html>
{% extends "base.html" %}
    {% block body_block%}

    <h1>Hello and welcome to the site!</h1>
    <h1>This is the index.html page</h1>
    {% endblock %}